local:
  research-center:
    - 'https://research-center-mosaic.dev.local'
  fund-center:
    - 'https://fund-center-mosaic.dev.local'
  factsheet-content:
    - 'https://factsheet-content-mosaic.dev.local'
  amundi-japan:
    - 'https://amundi-japan-mosaic.dev.local'
  demo-awf:
    - 'https://demo-awf-mosaic.dev.local'
  amt:
    - 'https://amt-mosaic.dev.local'
  amundi-indonesia:
    - 'https://amundi-indonesia-mosaic.dev.local'
  new-design:
    - 'https://new-design-mosaic.dev.local'
  amundi-retail:
    - 'https://amundi-global-retail-mosaic.dev.local'
    - 'https://amundi-aut-retail-mosaic.dev.local'
    - 'https://amundi-bel-retail-mosaic.dev.local'
    - 'https://amundi-bgr-retail-mosaic.dev.local'
    - 'https://amundi-cze-retail-mosaic.dev.local'
    - 'https://amundi-deu-retail-mosaic.dev.local'
    - 'https://amundi-fra-retail-mosaic.dev.local'
    - 'https://amundi-lux-retail-mosaic.dev.local'
    - 'https://amundi-pol-retail-mosaic.dev.local'
    - 'https://amundi-hun-retail-mosaic.dev.local'
    - 'https://amundi-irl-retail-mosaic.dev.local'
    - 'https://amundi-ita-retail-mosaic.dev.local'
    - 'https://amundi-esp-retail-mosaic.dev.local'
    - 'https://amundi-rou-retail-mosaic.dev.local'
    - 'https://amundi-svk-retail-mosaic.dev.local'
    - 'https://amundi-che-retail-mosaic.dev.local'
    - 'https://amundi-hkg-retail-mosaic.dev.local'
    - 'https://amundi-mys-retail-mosaic.dev.local'
    - 'https://amundi-twn-retail-mosaic.dev.local'
    - 'https://amundi-sgp-retail-mosaic.dev.local'
    - 'https://amundi-chn-retail-mosaic.dev.local'
    - 'https://amundi-idn-retail-mosaic.dev.local'
  amundi-distrib:
    - 'https://amundi-global-distrib-mosaic.dev.local'
    - 'https://amundi-aut-distrib-mosaic.dev.local'
    - 'https://amundi-deu-distrib-mosaic.dev.local'
    - 'https://amundi-ita-distrib-mosaic.dev.local'
    - 'https://amundi-irl-distrib-mosaic.dev.local'
    - 'https://amundi-esp-distrib-mosaic.dev.local'
  amundi-instit:
    - 'https://amundi-global-instit-mosaic.dev.local'
    - 'https://amundi-aut-instit-mosaic.dev.local'
    - 'https://amundi-bel-instit-mosaic.dev.local'
    - 'https://amundi-deu-instit-mosaic.dev.local'
    - 'https://amundi-irl-instit-mosaic.dev.local'
    - 'https://amundi-ita-instit-mosaic.dev.local'
    - 'https://amundi-fra-instit-mosaic.dev.local'
    - 'https://amundi-hun-instit-mosaic.dev.local'
    - 'https://amundi-lux-instit-mosaic.dev.local'
    - 'https://amundi-esp-instit-mosaic.dev.local'
    - 'https://amundi-gbr-instit-mosaic.dev.local'
    - 'https://amundi-che-instit-mosaic.dev.local'
    - 'https://amundi-can-instit-mosaic.dev.local'
    - 'https://amundi-tha-instit-mosaic.dev.local'
  corporate:
    - 'https://corporate-mosaic.dev.local'
  amundi-italy:
    - 'https://corepension-mosaic.dev.local'
    - 'https://secondapensione-mosaic.dev.local'
    - 'https://amundi-re-mosaic.dev.local'
dev:
  research-center:
    - 'https://dev-research-center.intramundi.com'
  fund-center:
    - 'https://dev-fund-center.intramundi.com'
  factsheet-content:
    - 'https://dev-factsheet-content.intramundi.com'
  amundi-japan:
    - 'https://dev-amundi-japan.intramundi.com'
  demo-awf:
    - 'https://dev-demo-awf.intramundi.com'
  amt:
    - 'https://dev-amunditechnology.intramundi.com'
  new-design:
    - 'https://dev-new-design-awf.intramundi.com'
  amundi-retail:
    - 'https://dev-amundi-global-retail.intramundi.com'
    - 'https://dev-amundi-aut-retail.intramundi.com'
    - 'https://dev-amundi-bel-retail.intramundi.com'
    - 'https://dev-amundi-bgr-retail.intramundi.com'
    - 'https://dev-amundi-cze-retail.intramundi.com'
    - 'https://dev-amundi-deu-retail.intramundi.com'
    - 'https://dev-amundi-fra-retail.intramundi.com'
    - 'https://dev-amundi-lux-retail.intramundi.com'
    - 'https://dev-amundi-pol-retail.intramundi.com'
    - 'https://dev-amundi-hun-retail.intramundi.com'
    - 'https://dev-amundi-irl-retail.intramundi.com'
    - 'https://dev-amundi-ita-retail.intramundi.com'
    - 'https://dev-amundi-esp-retail.intramundi.com'
    - 'https://dev-amundi-rou-retail.intramundi.com'
    - 'https://dev-amundi-svk-retail.intramundi.com'
    - 'https://dev-amundi-che-retail.intramundi.com'
    - 'https://dev-amundi-hkg-retail.intramundi.com'
    - 'https://dev-amundi-mys-retail.intramundi.com'
    - 'https://dev-amundi-twn-retail.intramundi.com'
    - 'https://dev-amundi-sgp-retail.intramundi.com'
    - 'https://dev-amundi-chn-retail.intramundi.com'
    - 'https://dev-amundi-idn-retail.intramundi.com'
  amundi-distrib:
    - 'https://dev-amundi-global-distrib.intramundi.com'
    - 'https://dev-amundi-aut-distrib.intramundi.com'
    - 'https://dev-amundi-deu-distrib.intramundi.com'
    - 'https://dev-amundi-ita-distrib.intramundi.com'
    - 'https://dev-amundi-esp-distrib.intramundi.com'
    - 'https://dev-amundi-irl-distrib.intramundi.com'
  amundi-instit:
    - 'https://dev-amundi-global-instit.intramundi.com'
    - 'https://dev-amundi-aut-instit.intramundi.com'
    - 'https://dev-amundi-bel-instit.intramundi.com'
    - 'https://dev-amundi-deu-instit.intramundi.com'
    - 'https://dev-amundi-irl-instit.intramundi.com'
    - 'https://dev-amundi-ita-instit.intramundi.com'
    - 'https://dev-amundi-fra-instit.intramundi.com'
    - 'https://dev-amundi-hun-instit.intramundi.com'
    - 'https://dev-amundi-lux-instit.intramundi.com'
    - 'https://dev-amundi-esp-instit.intramundi.com'
    - 'https://dev-amundi-gbr-instit.intramundi.com'
    - 'https://dev-amundi-che-instit.intramundi.com'
    - 'https://dev-amundi-can-instit.intramundi.com'
    - 'https://dev-amundi-tha-instit.intramundi.com'
  corporate:
    - 'https://dev-corporate-awf.intramundi.com'
  amundi-italy:
    - 'https://dev-corepension.intramundi.com'
    - 'https://dev-secondapensione.intramundi.com'
    - 'https://dev-amundi-re.intramundi.com'
rct:
  research-center:
    - 'https://rct-research-center.intramundi.com'
  fund-center:
    - 'https://rct-fund-center.intramundi.com'
  factsheet-content:
    - 'https://rct-factsheet-content.intramundi.com'
  amundi-japan:
    - 'https://rct-amundi-japan.intramundi.com'
  demo-awf:
    - 'https://rct-demo-awf.intramundi.com'
  amt:
    - 'https://rct-amunditechnology.intramundi.com'
  new-design:
    - 'https://rct-new-design-awf.intramundi.com'
  amundi-retail:
    - 'https://rct-amundi-global-retail.intramundi.com'
    - 'https://rct-amundi-aut-retail.intramundi.com'
    - 'https://rct-amundi-bel-retail.intramundi.com'
    - 'https://rct-amundi-bgr-retail.intramundi.com'
    - 'https://rct-amundi-cze-retail.intramundi.com'
    - 'https://rct-amundi-deu-retail.intramundi.com'
    - 'https://rct-amundi-fra-retail.intramundi.com'
    - 'https://rct-amundi-lux-retail.intramundi.com'
    - 'https://rct-amundi-pol-retail.intramundi.com'
    - 'https://rct-amundi-hun-retail.intramundi.com'
    - 'https://rct-amundi-irl-retail.intramundi.com'
    - 'https://rct-amundi-ita-retail.intramundi.com'
    - 'https://rct-amundi-esp-retail.intramundi.com'
    - 'https://rct-amundi-rou-retail.intramundi.com'
    - 'https://rct-amundi-svk-retail.intramundi.com'
    - 'https://rct-amundi-che-retail.intramundi.com'
    - 'https://rct-amundi-hkg-retail.intramundi.com'
    - 'https://rct-amundi-mys-retail.intramundi.com'
    - 'https://rct-amundi-twn-retail.intramundi.com'
    - 'https://rct-amundi-sgp-retail.intramundi.com'
    - 'https://rct-amundi-chn-retail.intramundi.com'
    - 'https://rct-amundi-idn-retail.intramundi.com'
  amundi-distrib:
    - 'https://rct-amundi-global-distrib.intramundi.com'
    - 'https://rct-amundi-aut-distrib.intramundi.com'
    - 'https://rct-amundi-deu-distrib.intramundi.com'
    - 'https://rct-amundi-ita-distrib.intramundi.com'
    - 'https://rct-amundi-esp-distrib.intramundi.com'
    - 'https://rct-amundi-irl-distrib.intramundi.com'
  amundi-instit:
    - 'https://rct-amundi-global-instit.intramundi.com'
    - 'https://rct-amundi-aut-instit.intramundi.com'
    - 'https://rct-amundi-bel-instit.intramundi.com'
    - 'https://rct-amundi-deu-instit.intramundi.com'
    - 'https://rct-amundi-irl-instit.intramundi.com'
    - 'https://rct-amundi-ita-instit.intramundi.com'
    - 'https://rct-amundi-fra-instit.intramundi.com'
    - 'https://rct-amundi-hun-instit.intramundi.com'
    - 'https://rct-amundi-lux-instit.intramundi.com'
    - 'https://rct-amundi-esp-instit.intramundi.com'
    - 'https://rct-amundi-gbr-instit.intramundi.com'
    - 'https://rct-amundi-che-instit.intramundi.com'
    - 'https://rct-amundi-can-instit.intramundi.com'
    - 'https://rct-amundi-tha-instit.intramundi.com'
  corporate:
    - 'https://rct-corporate-awf.intramundi.com'
  amundi-italy:
    - 'https://rct-corepension.intramundi.com'
    - 'https://rct-secondapensione.intramundi.com'
    - 'https://rct-amundi-re.intramundi.com'
ppr:
  research-center:
    - 'https://ppr-research-center.intramundi.com'
  fund-center:
    - 'https://ppr-fund-center.intramundi.com'
  factsheet-content:
    - 'https://ppr-factsheet-content.intramundi.com'
  amundi-japan:
    - 'https://ppr-amundi-japan.intramundi.com'
  demo-awf:
    - 'https://ppr-demo-awf.intramundi.com'
  amt:
    - 'https://ppr-amunditechnology.intramundi.com'
  amundi-retail:
    - 'https://ppr-amundi-global-retail.intramundi.com'
    - 'https://ppr-amundi-aut-retail.intramundi.com'
    - 'https://ppr-amundi-bel-retail.intramundi.com'
    - 'https://ppr-amundi-bgr-retail.intramundi.com'
    - 'https://ppr-amundi-cze-retail.intramundi.com'
    - 'https://ppr-amundi-deu-retail.intramundi.com'
    - 'https://ppr-amundi-fra-retail.intramundi.com'
    - 'https://ppr-amundi-lux-retail.intramundi.com'
    - 'https://ppr-amundi-pol-retail.intramundi.com'
    - 'https://ppr-amundi-hun-retail.intramundi.com'
    - 'https://ppr-amundi-irl-retail.intramundi.com'
    - 'https://ppr-amundi-ita-retail.intramundi.com'
    - 'https://ppr-amundi-esp-retail.intramundi.com'
    - 'https://ppr-amundi-rou-retail.intramundi.com'
    - 'https://ppr-amundi-svk-retail.intramundi.com'
    - 'https://ppr-amundi-che-retail.intramundi.com'
    - 'https://ppr-amundi-hkg-retail.intramundi.com'
    - 'https://ppr-amundi-mys-retail.intramundi.com'
    - 'https://ppr-amundi-twn-retail.intramundi.com'
    - 'https://ppr-amundi-sgp-retail.intramundi.com'
    - 'https://ppr-amundi-chn-retail.intramundi.com'
    - 'https://ppr-amundi-idn-retail.intramundi.com'
  amundi-distrib:
    - 'https://ppr-amundi-global-distrib.intramundi.com'
    - 'https://ppr-amundi-aut-distrib.intramundi.com'
    - 'https://ppr-amundi-deu-distrib.intramundi.com'
    - 'https://ppr-amundi-ita-distrib.intramundi.com'
    - 'https://ppr-amundi-esp-distrib.intramundi.com'
    - 'https://ppr-amundi-irl-distrib.intramundi.com'
  amundi-instit:
    - 'https://ppr-amundi-global-instit.intramundi.com'
    - 'https://ppr-amundi-aut-instit.intramundi.com'
    - 'https://ppr-amundi-bel-instit.intramundi.com'
    - 'https://ppr-amundi-deu-instit.intramundi.com'
    - 'https://ppr-amundi-irl-instit.intramundi.com'
    - 'https://ppr-amundi-ita-instit.intramundi.com'
    - 'https://ppr-amundi-fra-instit.intramundi.com'
    - 'https://ppr-amundi-hun-instit.intramundi.com'
    - 'https://ppr-amundi-lux-instit.intramundi.com'
    - 'https://ppr-amundi-esp-instit.intramundi.com'
    - 'https://ppr-amundi-gbr-instit.intramundi.com'
    - 'https://ppr-amundi-che-instit.intramundi.com'
    - 'https://ppr-amundi-can-instit.intramundi.com'
    - 'https://ppr-amundi-tha-instit.intramundi.com'
  corporate:
    - 'https://ppr-corporate-awf.intramundi.com'
  amundi-italy:
    - 'https://ppr-corepension.intramundi.com'
    - 'https://ppr-secondapensione.intramundi.com'
    - 'https://ppr-amundi-re.intramundi.com'
ppr-adsi:
  fund-center:
    - 'https://preprod.fc-fi.adsi.amundi.com/retail'
    - 'https://preprod.fc-fi.adsi.amundi.com/professional'
    - 'https://preprod.fc-no.adsi.amundi.com/retail'
    - 'https://preprod.fc-no.adsi.amundi.com/professional'
  amundi-retail:
    - 'https://preprod.awf-global.adsi.amundi.com/retail'
    - 'https://preprod.awf-fra.adsi.amundi.com/fr_part'
    - 'https://preprod.awf-lux.adsi.amundi.com/retail'
    - 'https://preprod.awf-lux.adsi.amundi.com/particuliers'
  amundi-instit:
    - 'https://preprod.awf-global.adsi.amundi.com/institutional'
    - 'https://preprod.awf-global.adsi.amundi.com/tha-instit'
    - 'https://preprod.awf-fra.adsi.amundi.com/fr_instit'
    - 'https://preprod.awf-lux.adsi.amundi.com/professional'
    - 'https://preprod.awf-lux.adsi.amundi.com/institutionnels'
  amundi-distrib:
    - 'https://preprod.awf-global.adsi.amundi.com/globaldistributor'
  amundi-italy:
    - 'https://preprod.awf-corepension.adsi.amundi.com/'
prd:
  research-center:
    - 'https://research-center.intramundi.com'
  fund-center:
    - 'https://fund-center.intramundi.com'
  factsheet-content:
    - 'https://factsheet-content.intramundi.com'
  amundi-japan:
    - 'https://amundi-japan.intramundi.com'
  demo-awf:
    - 'https://demo-awf.intramundi.com'
  amt:
    - 'https://amunditechnology.intramundi.com'
  amundi-retail:
    - 'https://amundi-global-retail.intramundi.com'
    - 'https://amundi-aut-retail.intramundi.com'
    - 'https://amundi-bel-retail.intramundi.com'
    - 'https://amundi-bgr-retail.intramundi.com'
    - 'https://amundi-cze-retail.intramundi.com'
    - 'https://amundi-deu-retail.intramundi.com'
    - 'https://amundi-fra-retail.intramundi.com'
    - 'https://amundi-lux-retail.intramundi.com'
    - 'https://amundi-pol-retail.intramundi.com'
    - 'https://amundi-hun-retail.intramundi.com'
    - 'https://amundi-irl-retail.intramundi.com'
    - 'https://amundi-ita-retail.intramundi.com'
    - 'https://amundi-esp-retail.intramundi.com'
    - 'https://amundi-rou-retail.intramundi.com'
    - 'https://amundi-svk-retail.intramundi.com'
    - 'https://amundi-che-retail.intramundi.com'
    - 'https://amundi-hkg-retail.intramundi.com'
    - 'https://amundi-mys-retail.intramundi.com'
    - 'https://amundi-twn-retail.intramundi.com'
    - 'https://amundi-sgp-retail.intramundi.com'
    - 'https://amundi-chn-retail.intramundi.com'
    - 'https://amundi-idn-retail.intramundi.com'
  amundi-distrib:
    - 'https://amundi-global-distrib.intramundi.com'
    - 'https://amundi-aut-distrib.intramundi.com'
    - 'https://amundi-deu-distrib.intramundi.com'
    - 'https://amundi-ita-distrib.intramundi.com'
    - 'https://amundi-esp-distrib.intramundi.com'
    - 'https://amundi-irl-distrib.intramundi.com'
  amundi-instit:
    - 'https://amundi-global-instit.intramundi.com'
    - 'https://amundi-aut-instit.intramundi.com'
    - 'https://amundi-bel-instit.intramundi.com'
    - 'https://amundi-deu-instit.intramundi.com'
    - 'https://amundi-irl-instit.intramundi.com'
    - 'https://amundi-ita-instit.intramundi.com'
    - 'https://amundi-fra-instit.intramundi.com'
    - 'https://amundi-hun-instit.intramundi.com'
    - 'https://amundi-lux-instit.intramundi.com'
    - 'https://amundi-esp-instit.intramundi.com'
    - 'https://amundi-gbr-instit.intramundi.com'
    - 'https://amundi-che-instit.intramundi.com'
    - 'https://amundi-can-instit.intramundi.com'
    - 'https://amundi-tha-instit.intramundi.com'
  corporate:
    - 'https://corporate-awf.intramundi.com'
  amundi-italy:
    - 'https://corepension.intramundi.com'
    - 'https://secondapensione.intramundi.com'
    - 'https://amundi-re.intramundi.com'
prd-adsi:
  amundi-retail:
    - 'https://awf-global-instit.adsi.amundi.com/retail'
    - 'https://awf-fra-retail.adsi.amundi.com/fr_part'
    - 'https://awf-lux-instit.adsi.amundi.com/retail'
    - 'https://awf-lux-instit.adsi.amundi.com/particuliers'
  amundi-instit:
    - 'https://awf-global-instit.adsi.amundi.com/institutional'
    - 'https://awf-fra-retail.adsi.amundi.com/fr_instit'
    - 'https://awf-lux-instit.adsi.amundi.com/professional'
    - 'https://awf-lux-instit.adsi.amundi.com/institutionnels'
  amundi-distrib:
    - 'https://awf-global-instit.adsi.amundi.com/globaldistributor'
  amundi-italy:
    - 'https://awf-corepension.adsi.amundi.com/'
prd-internet:
  research-center:
    - 'https://research-center.amundi.com'
  fund-center:
    - 'https://www.amundi.com.cy/retail'
    - 'https://www.amundi.com.cy/professional'
    - 'https://www.amundi.dk/retail'
    - 'https://www.amundi.dk/professional'
    - 'https://www.amundi.fi/retail'
    - 'https://www.amundi.fi/professional'
    - 'https://www.amundi.gr/retail'
    - 'https://www.amundi.gr/professional'
    - 'https://www.amundi.nl/retail'
    - 'https://www.amundi.nl/professional'
    - 'https://www.amundi.no/retail'
    - 'https://www.amundi.no/professional'
    - 'https://www.amundi.pt/retail'
    - 'https://www.amundi.pt/professional'
    - 'https://www.amundi.se/retail'
    - 'https://www.amundi.se/professional'
    - 'https://www.amundi.si/retail'
    - 'https://www.amundi.si/professional'
  amundi-japan:
    - 'https://www.amundi.co.jp'
  amt:
    - 'https://www.amunditechnology.com'
  amundi-indonesia:
    - 'https://www.amundi.co.id'
    - 'https://www.amundi.id'
  amundi-instit:
    - 'https://www.amundi.com/institutional'
    - 'https://www.amundi.de/institutional'
    - 'https://www.amundi.at/institutionelle_firmenkunden'
    - 'https://www.amundi.be/professional'
    - 'https://www.amundi.it/investitori_qualificati'
    - 'https://www.amundi.fr/fr_instit'
    - 'https://www.amundi.hu/intezmenyi'
    - 'https://www.amundi.lu/professional'
    - 'https://www.amundi.lu/institutionnels'
    - 'https://www.amundi.ch/professional'
    - 'https://www.amundi.co.uk/professional'
    - 'https://www.amundi.ca/professional'
    - 'https://www.amundi.ca/institutionnels'
  amundi-retail:
    - 'https://www.amundi.de/privatanleger'
    - 'https://www.amundi.at/privatkunden'
    - 'https://www.amundi.be/particuliers '
    - 'https://www.amundi.be/individuele_beleggers'
    - 'https://www.amundi.bg/retail'
    - 'https://www.amundi.fr/fr_part'
    - 'https://www.amundi.hu/lakossagi'
    - 'https://www.amundi.it/investitori_privati'
    - 'https://www.amundi.lu/retail'
    - 'https://www.amundi.lu/particuliers'
    - 'https://www.amundi.pl/Inwestorzy_indywidualni'
    - 'https://www.amundi.cz/produkty'
    - 'https://www.amundi.ro/retail'
    - 'https://www.amundi.sk/klienti'
    - 'https://www.amundi.ch/particuliers'
    - 'https://www.amundi.ch/retail'
    - 'https://www.amundi.ch/privatanleger'
    - 'https://www.amundi.com.hk/zh_retail'
    - 'https://www.amundi.com.hk/retail'
    - 'https://www.amundi.com.my/retail'
    - 'https://www.amundi.com.tw/retail'
    - 'https://www.amundi.com.sg/retail'
    - 'https://www.amundi.com.cn/zh_retail'
    - 'https://www.amundi.ie/retail'
    - 'https://www.amundi.es/retail'
  amundi-distrib:
    - 'https://www.amundi.com/globaldistributor'
    - 'https://www.amundi.de/vertriebspartner'
    - 'https://www.amundi.at/vertriebspartner'
    - 'https://www.amundi.it/investitori_qualificati'
    - 'https://www.amundi.ie/professional'
    - 'https://www.amundi.es/inversor-profesional'
  amundi-italy:
    - 'https://www.corepension.it/'
    - 'https://www.secondapensione.it/'
    - 'https://www.amundi-re.it/'
