<?php

/**
 * Implements hook_module_implements_alter().
 *
 * @param array<mixed> $implementations
 * @param string $hook
 */
function custom_field_permissions_instance_module_implements_alter(array &$implementations, string $hook) : void {
  // Ensure that custom_field_permissions_instance runs after field_permissions
  if (isset($implementations['custom_field_permissions_instance']) && isset($implementations['field_permissions'])) {
    $saved = $implementations['custom_field_permissions_instance'];
    unset($implementations['custom_field_permissions_instance']);
    $implementations['custom_field_permissions_instance'] = $saved;
  }
}

